### ISSUE TITLE
ERROR {org.wso2.micro.integrator.registry.MicroIntegratorRegistry} - Couldn't create folder: secure-vault

### ISSUE THREAD

**Issue by starsmall-xiaoqq** [wso2/devstudio-tooling-ei#1168]
**Description:**

when creating a integration project, click "Export project artifacts and run", the console shows error of "ERROR {org.wso2.micro.integrator.registry.MicroIntegratorRegistry} - Couldn't create folder: secure-vault". 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
windows 10, integration studio 7.0.0
**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
@starsmall-xiaoqq 
What is the Windows directory path to your extracted Integration Studio distribution? And, can you send the full error stack that is being logged there?

**Comment by starsmall-xiaoqq** [comment]
hi,
The path is C:\Program Files\WSO2\IntegrationStudio.
The wso2carbon.log is heading as:
TID: [2020-07-09 12:02:19,280]  WARN {org.wso2.config.mapper.ConfigParser} - Configurations Changed in :conf\axis2\axis2.xml {org.wso2.config.mapper.ConfigParser}
TID: [2020-07-09 12:02:19,315]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory C:/Program Files/WSO2/IntegrationStudio/runtime/microesb {org.wso2.config.mapper.ConfigParser}
TID: [2020-07-09 12:02:20,711]  INFO {org.wso2.config.mapper.ConfigParser} - Writing Metadata Entries... {org.wso2.config.mapper.ConfigParser}
[2020-07-09 12:02:38,171] ERROR {org.wso2.micro.integrator.registry.MicroIntegratorRegistry} - Couldn't create folder: secure-vault
[2020-07-09 12:02:38,181] ERROR {org.wso2.micro.integrator.registry.MicroIntegratorRegistry} - Error when adding a new resource org.apache.synapse.SynapseException: Couldn't create folder: secure-vault
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.handleException(MicroIntegratorRegistry.java:575)
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.createFolder(MicroIntegratorRegistry.java:811)
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.addResource(MicroIntegratorRegistry.java:730)
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.newResource(MicroIntegratorRegistry.java:493)
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.initSecurityRepo(MicroIntegratorRegistry.java:123)
	at org.wso2.micro.integrator.registry.MicroIntegratorRegistry.<init>(MicroIntegratorRegistry.java:113)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.synapse.config.xml.RegistryFactory.createRegistry(RegistryFactory.java:57)
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineRegistry(SynapseXMLConfigurationFactory.java:145)
	at org.apache.synapse.config.xml.MultiXMLConfigurationBuilder.createRegistry(MultiXMLConfigurationBuilder.java:199)
	at org.apache.synapse.config.xml.MultiXMLConfigurationBuilder.getConfiguration(MultiXMLConfigurationBuilder.java:125)
	at org.apache.synapse.config.SynapseConfigurationBuilder.getConfiguration(SynapseConfigurationBuilder.java:107)
	at org.apache.synapse.Axis2SynapseController.createSynapseConfiguration(Axis2SynapseController.java:473)
	at org.wso2.micro.integrator.initializer.CarbonSynapseController.createSynapseConfiguration(CarbonSynapseController.java:162)
	at org.apache.synapse.ServerManager.start(ServerManager.java:179)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:298)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.micro.integrator.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)

**Comment by prabushi** [comment]
@starsmall-xiaoqq
The mentioned error occurs when the Micro Integrator runs in **C:\\Program Files** directory and when it does not own the required permission. Since the 'C:\\Program Files' is used to run system-related software, we do not recommend extracting the Integration Studio to this location. In order to avoid this error, you need to either;
- Extract the Integration Studio into another location (eg: C:\\Wso2\IntegrationStudio)
- Run the Integration Studio, which is at C:\\Program Files, with administrative permissions

**Comment by starsmall-xiaoqq** [comment]
Thank you @prabushi ,  I change the path and the problem disappeared.
