### ISSUE TITLE
Child element doesn't inherit namespace URL from the parent element

### ISSUE THREAD

**Issue by isuruirj** [wso2/devstudio-tooling-ei#236]
**Description:**
Please refer to below configuration. This is a part of my proxy configuration. I could save this configuration through management console source view without any issue and when I try to save the same configuration in eclipse dev studio it gives below error message.

        <inSequence>
            <switch source="//abc:type" xmlns:abc="http://abcd.com/">
                <case regex="XYZ">
                    <payloadFactory media-type="xml">
                        <format>
                            <abc:getName>
                                <id xmlns="">$1</id>
                            </abc:getName>
                        </format>
                        <args>
                            <arg evaluator="xml" expression="//abc:id"/>
                        </args>
                    </payloadFactory>
                </case>
                <default>
                    <payloadFactory media-type="xml">
                        <format>
                            <abc:saveName>
                                <id xmlns="">$1</id>
                            </abc:saveName>
                        </format>
                        <args>
                            <arg evaluator="xml" expression="//abc:id"/>
                        </args>
                    </payloadFactory>
                </default>
            </switch>
        </inSequence>

`org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxParsingException: Undeclared namespace prefix "abc"
 at [row,col {unknown-source}]: [1,59]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
	at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
	at org.apache.axiom.om.impl.llom.OMElementImpl.cloneOMElement(OMElementImpl.java:1034)
	at org.apache.synapse.config.xml.PayloadFactoryMediatorFactory.createSpecificMediator(PayloadFactoryMediatorFactory.java:71)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:94)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.validator.ProcessSourceView.validateMediators(ProcessSourceView.java:944)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.validator.ProcessSourceView.validate(ProcessSourceView.java:701)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.validator.ProcessSourceView.mediatorValidation(ProcessSourceView.java:646)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.validator.ProcessSourceView.synapseValidation(ProcessSourceView.java:539)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.validator.ProcessSourceView.validateSynapseContent(ProcessSourceView.java:172)
	at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor$8.run(EsbMultiPageEditor.java:1103)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4034)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3701)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: com.ctc.wstx.exc.WstxParsingException: Undeclared namespace prefix "abc"
 at [row,col {unknown-source}]: [1,59]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:606)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:479)
	at com.ctc.wstx.sr.InputElementStack.resolveAndValidateElement(InputElementStack.java:507)
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2977)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2837)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 36 more`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_192
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Duplicate issue https://github.com/wso2/product-ei/issues/3308
