### ISSUE TITLE
[1.1.0] NullPointerException on new proxy in workspace with existing breakpoints

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/devstudio-tooling-ei#56]
This bug is not easily reproducible. We have an installation where a local WSO2 EI server was configured in an Eclipse workspace. The workspace was deleted and a new workspace was created with the same local WSO2 EI server.

In that workspace, we created a new proxy service and renamed the xml file. The content is:

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="TestServiceStub" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence/>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>
```

When trying to save the new file in Eclipse, a NullPointerException is thrown :

```
!ENTRY org.eclipse.ui 2 0 2017-07-18 09:07:06.810
!MESSAGE Save All Failed
!STACK 0
java.lang.NullPointerException
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.debugger.debugpoint.builder.impl.AbstractESBDebugPointBuilder.getMediatorPositionInFaultSeq(AbstractESBDebugPointBuilder.java:615)
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.debugger.debugpoint.builder.impl.AbstractESBDebugPointBuilder.getMediatorPositionInFaultSeq(AbstractESBDebugPointBuilder.java:578)
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.debugger.debugpoint.builder.impl.ProxyDebugPointBuilder.updateExistingDebugPoints(ProxyDebugPointBuilder.java:86)
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.debugger.utils.ESBDebuggerUtil.modifyDebugPointsointsAfterMediatorAddition(ESBDebuggerUtil.java:170)
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.debugger.utils.ESBDebuggerUtil.updateModifiedDebugPoints(ESBDebuggerUtil.java:196)
        at org.wso2.developerstudio.eclipse.gmf.esb.diagram.part.EsbMultiPageEditor.doSave(EsbMultiPageEditor.java:989)
        at org.eclipse.ui.internal.DefaultSaveable.doSave(DefaultSaveable.java:51)
        at org.eclipse.ui.Saveable.doSave(Saveable.java:216)
        at org.eclipse.ui.internal.SaveableHelper.doSaveModel(SaveableHelper.java:357)
        at org.eclipse.ui.internal.SaveablesList$3.run(SaveablesList.java:665)
        at org.eclipse.ui.internal.SaveableHelper$5.run(SaveableHelper.java:285)
        at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
        at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2181)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2177)
        at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:293)
        at org.eclipse.ui.internal.SaveablesList.saveModels(SaveablesList.java:675)
        at org.eclipse.ui.internal.WorkbenchPage.saveAll(WorkbenchPage.java:3660)
        at org.eclipse.ui.internal.WorkbenchPage.saveAllEditors(WorkbenchPage.java:3638)
        at org.eclipse.ui.internal.handlers.SaveAllHandler.execute(SaveAllHandler.java:48)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
        at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:160)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
        at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:462)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

It seems that the Tooling is trying to parse the list of mediators from the fault sequence, but that sequence is empty.

A quick fix is to remove the server configuration from the tooling and start with a newly extracted WSO2 EI server installation, which seems to reset the breakpoints/server configuration.

**Comment by rosensilva** [comment]
Fixed in the latest Integration Studio 7.0.0 Milestone
