### ISSUE TITLE
Unable to run a hello world service while the Micro Integrator  server crashed.

### ISSUE THREAD

**Issue by huanghongqing** [wso2/devstudio-tooling-ei#684]
**Description:**
Add a hello world service and select "Export project atrifacts & run",the Micro Integrator crash

**Affected Product Version:**
WSO2-Integration-Studio-7.0.0-linux-gtk-x86_64
**OS, DB, other environment details and versions:**    
os: Manjaro kde,linux 4.19.91-1
java vm:
openjdk version "1.8.0_232"

**Steps to reproduce:**
At welcome page ,select "hello world service ",and  Right click on the respective Composite Application project and select Export project atrifacts & run from menu.

then we got the error as below:
`[2020-01-09 20:16:52,956]  WARN {org.wso2.micro.integrator.management.apis.ManagementInternalApi} - Micro Integrator Management REST API is enabled
[2020-01-09 20:16:54,256] FATAL {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Exception encountered in the HTTP Listener. No more connections will be accepted by this transport org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357)
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:536)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:63)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:575)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:306)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	... 1 more`

**Comment by prabushi** [comment]
Related to https://github.com/wso2/micro-integrator/issues/1129

**Comment by prabushi** [comment]
@huanghongqing
Can you specify the additional configurations that you have done for the embedded MI, and how you have configured them? It seems you have enabled the Management REST API? And, do you continuously see this error while starting the embedded MI or is it intermittent?
