### ISSUE TITLE
[DSS] Editing existing dbs file after update to 7.0.0.202002290706 is not working

### ISSUE THREAD

**Issue by jpvadell** [wso2/devstudio-tooling-ei#740]
After the update, DSS Editor fails to open an existing configured dbs.

On my Mac, after changing some things (*), I could see the configurations from the editor. But a mate with Windows 10 it's impossible to open it.

This are the main error when we try to open the file.

org.wso2.developerstudio.eclipse.webui.core.exception.WebUIException: Error executing Script:Function Call:loadFileContent Browser returned execution failed status.
	at org.wso2.developerstudio.eclipse.webui.core.editor.AbstractWebBasedEditor.executeScriptOnBrowser(AbstractWebBasedEditor.java:225)
	at org.wso2.developerstudio.eclipse.webui.core.editor.AbstractWebBasedEditor$2.completed(AbstractWebBasedEditor.java:152)
	at org.eclipse.swt.browser.WebKit.webView_didFinishLoadForFrame(WebKit.java:807)
	at org.eclipse.swt.browser.WebKit.browserProc(WebKit.java:323)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5149)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5531)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3693)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

(*) Some things that I changed to get this working (Only in Mac).

Original:
`<data name="Producers_DSS">`
New:
` <data name="Producers_DSS" **serviceGroup="" serviceNamespace="" transports="local http https"**>`

Original:
  ```
<resource method="GET" path="/codes">
    <call-query href="ProducerCodesByUser">
      <with-param name="username" query-param="username" />
    </call-query>
  </resource>
```
New:
```
  <resource method="**get**" path="/codes">
    **<description />**
    <call-query href="ProducerCodesByUser">
      <with-param name="username" query-param="username" />
    </call-query>
  </resource>
```

Original:
```
  <config id="ORACLE_PCUSER_READ">
    <property name="carbon_datasource_name">ORACLE_PCUSER_READ</property>
  </config>
```
New:
```
  <config id="ORACLE_PCUSER_READ" **enableOData="false"**>
    <property name="carbon_datasource_name">ORACLE_PCUSER_READ</property>
  </config>
```

**Comment by jpvadell** [comment]
Hi, I updated to 7.0.0.202003060912 and I found only one problem

If your Data Service is defined like this:
<data name="Producers_DSS">
Is not working, but if I add the attributes... works.

<data name="Producers_DSS" serviceGroup="" serviceNamespace="" transports="local http https">

**Comment by jpvadell** [comment]
The error that appears at the logs is:
org.wso2.developerstudio.eclipse.webui.core.exception.WebUIException: Error executing Script:Function Call:loadFileContent Browser returned execution failed status.
	at org.wso2.developerstudio.eclipse.webui.core.editor.AbstractWebBasedEditor.executeScriptOnBrowser(AbstractWebBasedEditor.java:225)
	at org.wso2.developerstudio.eclipse.webui.core.editor.AbstractWebBasedEditor$2.completed(AbstractWebBasedEditor.java:152)
	at org.eclipse.swt.browser.WebKit.webView_didFinishLoadForFrame(WebKit.java:807)
	at org.eclipse.swt.browser.WebKit.browserProc(WebKit.java:323)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5149)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5531)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3693)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by prabushi** [comment]
@jpvadell 
Fix for the above mentioned issue is now available as an update. Please try with new updates.
