### ISSUE TITLE
Error while deploying DSS without having Row name

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/devstudio-tooling-ei#906]
**Description:**
The following error occurs while deploying MySQL DSS application which created without defining Row Name in the result output mapping section.
```
ERROR {org.wso2.micro.integrator.dataservices.core.DBDeployer} - The RDBMSDataService-1.0.0.dbs service, which is not valid, caused {1} DS Fault Message: The request '_getgetemployee' contains the query with id 'getEmployee' contains an XML result with no element wrapper.
DS Code: UNKNOWN_ERROR

	at org.wso2.micro.integrator.dataservices.core.DBDeployer.validateRequestQueryResults(DBDeployer.java:777)
	at org.wso2.micro.integrator.dataservices.core.DBDeployer.validateDataService(DBDeployer.java:705)
	at org.wso2.micro.integrator.dataservices.core.DBDeployer.createDBService(DBDeployer.java:823)
	at org.wso2.micro.integrator.dataservices.core.DBDeployer.processService(DBDeployer.java:1164)
	at org.wso2.micro.integrator.dataservices.core.DBDeployer.deploy(DBDeployer.java:196)
```
Row Name should have default value of `Entries` in for rowName attribute.

**Affected Product Version:**
Integration Studio 7.0.2

**Steps to reproduce:**
Create MySQL data service without defining Row Name for result output mapping.

**Comment by DMadhuranga** [comment]
`rowName` is an optional field. But `group by element` is a required field. This error occurs when `group by element` is left empty.  It would be helpful to validate in the DataService UI whether `group by element` is empty.
