### ISSUE TITLE
[Data Mapper] Concat operation does not work for xml-to-xml mapping

### ISSUE THREAD

**Issue by milindaperera** [wso2/devstudio-tooling-ei#924]
**Description:**
String Concat operation does not work for xml-to-xml data mapping

<img width="1096" alt="Screenshot 2020-04-20 at 13 38 46" src="https://user-images.githubusercontent.com/7402364/79729168-b6539a80-830c-11ea-88e6-fcfeff89df05.png">

Resulting XSLT snippet 
```xml
<address>
                <text>
                    <xsl:value-of select=""/>
                </text>
                <line>
                    <xsl:value-of select="soapenv:Envelope/soapenv:Body/pns:Patients/pns:Patient/pns:address1"/>
                </line>
                <city>
                    <xsl:value-of select="soapenv:Envelope/soapenv:Body/pns:Patients/pns:Patient/pns:city"/>
                </city>
                <postalCode>
                    <xsl:value-of select="soapenv:Envelope/soapenv:Body/pns:Patients/pns:Patient/pns:postalcode"/>
                </postalCode>
                <country>
                    <xsl:value-of select="soapenv:Envelope/soapenv:Body/pns:Patients/pns:Patient/pns:country"/>
                </country>
                <period/>
            </address>
```

**Affected Product Version:**
7.0.2

**Comment by milindaperera** [comment]
Input:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <pns:Patients xmlns:pns="http://org.wso2.sample.hospital/patient">
            <pns:Patient>
                <pns:id>12345678</pns:id>
                <pns:fname>efdd</pns:fname>
                <pns:lname>dsd</pns:lname>
                <pns:gender>M</pns:gender>
                <pns:dob>1912-06-06</pns:dob>
                <pns:maritalStatus>S</pns:maritalStatus>
                <pns:language>Sinhala</pns:language>
                <pns:address1>sddsdsd</pns:address1>
                <pns:address2>sdsd</pns:address2>
                <pns:city>sds</pns:city>
                <pns:postalcode>11350</pns:postalcode>
                <pns:country>SL</pns:country>
                <pns:telecom>073243245234</pns:telecom>
            </pns:Patient>
        </pns:Patients>
    </soapenv:Body>
</soapenv:Envelope>
```

Output:
```xml
<Patient>
    <id>sample-id</id>
    <meta>
        <versionId>1</versionId>
        <lastUpdated>2016-05-16T00:55:52Z</lastUpdated>
        <source>[uri]</source>
        <profile>profile</profile>
        <multi-profile>
            <profile>profile1</profile>
            <profile>profile2</profile>
        </multi-profile>
        <!--Security code must match FHIR Core Security Labels Ref: http://hl7.org/fhir/security-labels.html-->
        <security>R</security>
        <multi-security>
            <code>R</code>
            <code>GOV</code>
        </multi-security>
        <tag>actionable</tag>
    </meta>
    <language>en</language>
    <text>
        <status>generated</status>
        <div>xhtml div</div>
    </text>
    <identifier>
        <use>usual</use>
        <type>MR</type>
        <system>urn:oid:1.2.36.146.595.217.0.1</system>
        <value>12345</value>
        <period>
            <start>2001-05-06</start>
            <end>2001-05-06</end>
        </period>
        <assigner>
            <reference>org/121443</reference>
            <display>Acme Healthcare</display>
        </assigner>
    </identifier>
    <active>true</active>
    <name>
        <use>official</use>
        <text>James Chalmers</text>
        <family>Chalmers</family>
        <given>Peter</given>
        <givenNames>James</givenNames>
        <givenNames>James</givenNames>
        <prefix>Dr.</prefix>
        <suffix>Phd</suffix>
        <period>
            <start>2001-05-06</start>
            <end>2001-05-06</end>
        </period>
    </name>
    <telecom>
        <system>phone</system>
        <value>(03) 5555 6473</value>
        <use>work</use>
        <rank>1</rank>
        <period>
            <start>2001-05-06</start>
            <end>2001-05-06</end>
        </period>
    </telecom>
    <gender>male</gender>
    <birthDate>1974-12-25</birthDate>
    <address>
        <use>home</use>
        <type>both</type>
        <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
        <line>534 Erewhon St</line>
        <lines>534 Erewhon St</lines>
        <lines>534 Erewhon St</lines>
        <city>PleasantVille</city>
        <district>Rainbow</district>
        <state>Vic</state>
        <postalCode>3999</postalCode>
        <country>US</country>
        <period>
            <start>1974-12-25</start>
            <end>1974-12-25</end>
        </period>
    </address>
    <maritalStatus>S</maritalStatus>
    <photo>#####</photo>
    <contact>
        <relationshipCode>N</relationshipCode>
        <relationshipCodes>N</relationshipCodes>
        <relationshipCodes>N</relationshipCodes>
        <name>
            <use>official</use>
            <text>James Chalmers</text>
            <family>Chalmers</family>
            <given>Peter</given>
            <givenNames>James</givenNames>
            <givenNames>James</givenNames>
            <prefix>Dr.</prefix>
            <suffix>Phd</suffix>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </name>
        <telecom>
            <system>phone</system>
            <value>(03) 5555 6473</value>
            <use>work</use>
            <rank>1</rank>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </telecom>
        <address>
            <use>home</use>
            <type>both</type>
            <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
            <line>534 Erewhon St</line>
            <lines>534 Erewhon St</lines>
            <lines>534 Erewhon St</lines>
            <city>PleasantVille</city>
            <district>Rainbow</district>
            <state>Vic</state>
            <postalCode>3999</postalCode>
            <country>US</country>
            <period>
                <start>1974-12-25</start>
                <end>1974-12-25</end>
            </period>
        </address>
        <gender>female</gender>
        <organization>
            <reference>org/121443</reference>
            <display>Acme Healthcare</display>
        </organization>
        <period>
            <start>1974-12-25</start>
            <end>1974-12-25</end>
        </period>
    </contact>
    <communication>
        <language>
            <coding>nl</coding>
            <text>Nederlands</text>
        </language>
        <preferred>true</preferred>
    </communication>
    <generalPractitioner>
        <reference>Practitioner/21B</reference>
        <type>Practitioner</type>
        <display>Too-Onebee</display>
    </generalPractitioner>
    <managingOrganization>
        <reference>Organization/f001</reference>
        <display>Burgers University Medical Centre</display>
    </managingOrganization>
    <link>
        <reference>Patient/21B</reference>
        <type>Patient</type>
        <display>patientName</display>
        <LinkType>refer</LinkType>
    </link>

    <multiple-elements>
        <identifier>
            <use>usual</use>
            <type>MR</type>
            <system>urn:oid:1.2.36.146.595.217.0.1</system>
            <value>12345</value>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
            <assigner>
                <reference>org/121443</reference>
                <display>Acme Healthcare</display>
            </assigner>
        </identifier>
        <identifier>
            <use>usual</use>
            <type>MR</type>
            <system>urn:oid:1.2.36.146.595.217.0.1</system>
            <value>12345</value>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
            <assigner>
                <reference>org/121443</reference>
                <display>Acme Healthcare</display>
            </assigner>
        </identifier>

        <name>
            <use>official</use>
            <text>James Chalmers</text>
            <family>Chalmers</family>
            <given>Peter</given>
            <givenNames>James</givenNames>
            <givenNames>James</givenNames>
            <prefix>Dr.</prefix>
            <suffix>Phd</suffix>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </name>
        <name>
            <use>official</use>
            <text>James Chalmers</text>
            <family>Chalmers</family>
            <given>Peter</given>
            <givenNames>James</givenNames>
            <givenNames>James</givenNames>
            <prefix>Dr.</prefix>
            <suffix>Phd</suffix>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </name>

        <telecom>
            <system>phone</system>
            <value>(03) 5555 6473</value>
            <use>work</use>
            <rank>1</rank>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </telecom>
        <telecom>
            <system>phone</system>
            <value>(03) 5555 6473</value>
            <use>work</use>
            <rank>1</rank>
            <period>
                <start>2001-05-06</start>
                <end>2001-05-06</end>
            </period>
        </telecom>

        <address>
            <use>home</use>
            <type>both</type>
            <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
            <line>534 Erewhon St</line>
            <lines>534 Erewhon St</lines>
            <lines>534 Erewhon St</lines>
            <city>PleasantVille</city>
            <district>Rainbow</district>
            <state>Vic</state>
            <postalCode>3999</postalCode>
            <country>US</country>
            <period>
                <start>1974-12-25</start>
                <end>1974-12-25</end>
            </period>
        </address>
        <address>
            <use>home</use>
            <type>both</type>
            <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
            <line>534 Erewhon St</line>
            <lines>534 Erewhon St</lines>
            <lines>534 Erewhon St</lines>
            <city>PleasantVille</city>
            <district>Rainbow</district>
            <state>Vic</state>
            <postalCode>3999</postalCode>
            <country>US</country>
            <period>
                <start>1974-12-25</start>
                <end>1974-12-25</end>
            </period>
        </address>

        <photo>#####</photo>
        <photo>#####</photo>

        <contact>
            <relationshipCode>N</relationshipCode>
            <relationshipCodes>N</relationshipCodes>
            <relationshipCodes>N</relationshipCodes>
            <name>
                <use>official</use>
                <text>James Chalmers</text>
                <family>Chalmers</family>
                <given>Peter</given>
                <givenNames>James</givenNames>
                <givenNames>James</givenNames>
                <prefix>Dr.</prefix>
                <suffix>Phd</suffix>
                <period>
                    <start>2001-05-06</start>
                    <end>2001-05-06</end>
                </period>
            </name>
            <telecom>
                <system>phone</system>
                <value>(03) 5555 6473</value>
                <use>work</use>
                <rank>1</rank>
                <period>
                    <start>2001-05-06</start>
                    <end>2001-05-06</end>
                </period>
            </telecom>
            <address>
                <use>home</use>
                <type>both</type>
                <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
                <line>534 Erewhon St</line>
                <lines>534 Erewhon St</lines>
                <lines>534 Erewhon St</lines>
                <city>PleasantVille</city>
                <district>Rainbow</district>
                <state>Vic</state>
                <postalCode>3999</postalCode>
                <country>US</country>
                <period>
                    <start>1974-12-25</start>
                    <end>1974-12-25</end>
                </period>
            </address>
            <gender value="female"/>
            <organization>
                <reference>org/121443</reference>
                <display>Acme Healthcare</display>
            </organization>
            <period>
                <start>1974-12-25</start>
                <end>1974-12-25</end>
            </period>
        </contact>
        <contact>
            <relationshipCode>N</relationshipCode>
            <relationshipCodes>N</relationshipCodes>
            <relationshipCodes>N</relationshipCodes>
            <name>
                <use>official</use>
                <text>James Chalmers</text>
                <family>Chalmers</family>
                <given>Peter</given>
                <givenNames>James</givenNames>
                <givenNames>James</givenNames>
                <prefix>Dr.</prefix>
                <suffix>Phd</suffix>
                <period>
                    <start>2001-05-06</start>
                    <end>2001-05-06</end>
                </period>
            </name>
            <telecom>
                <system>phone</system>
                <value>(03) 5555 6473</value>
                <use>work</use>
                <rank>1</rank>
                <period>
                    <start>2001-05-06</start>
                    <end>2001-05-06</end>
                </period>
            </telecom>
            <address>
                <use>home</use>
                <type>both</type>
                <text>534 Erewhon St PeasantVille, Rainbow, Vic  3999</text>
                <line>534 Erewhon St</line>
                <lines>534 Erewhon St</lines>
                <lines>534 Erewhon St</lines>
                <city>PleasantVille</city>
                <district>Rainbow</district>
                <state>Vic</state>
                <postalCode>3999</postalCode>
                <country>US</country>
                <period>
                    <start>1974-12-25</start>
                    <end>1974-12-25</end>
                </period>
            </address>
            <gender value="female"/>
            <organization>
                <reference>org/121443</reference>
                <display>Acme Healthcare</display>
            </organization>
            <period>
                <start>1974-12-25</start>
                <end>1974-12-25</end>
            </period>
        </contact>

        <communication>
            <language>
                <coding>nl</coding>
                <text>Nederlands</text>
            </language>
            <preferred>true</preferred>
        </communication>
        <communication>
            <language>
                <coding>nl</coding>
                <text>Nederlands</text>
            </language>
            <preferred>true</preferred>
        </communication>

        <generalPractitioner>
            <reference>Practitioner/21B</reference>
            <type>Practitioner</type>
            <display>Too-Onebee</display>
        </generalPractitioner>
        <generalPractitioner>
            <reference>Practitioner/21B</reference>
            <type>Practitioner</type>
            <display>Too-Onebee</display>
        </generalPractitioner>

        <link>
            <reference>Patient/21B</reference>
            <type>Patient</type>
            <display>patientName</display>
            <LinkType>refer</LinkType>
        </link>
        <link>
            <reference>Patient/21B</reference>
            <type>Patient</type>
            <display>patientName</display>
            <LinkType>refer</LinkType>
        </link>
    </multiple-elements>
</Patient>
```

**Comment by milindaperera** [comment]
@DMadhuranga 
I rechecked concat operation again. It works fine for 2 input but fails for 3 inputs. And gives following error in runtime

```
[2020-04-21 00:17:16,849] [EI-Core]  INFO - LogMediator To: /fhir/rest/r4/Patient/12345678, MessageID: urn:uuid:938cd5a6-9c47-4ebd-bf4d-ae4439fbc5bf correlation_id : be59e279-b446-4771-bca8-0e4c2df6004e, Direction: request, SEQUENCE_START = retrievePatientFromId
Error at xsl:value-of on line 1 column 2263
  XPST0003 XPath syntax error at char 0 in {}:
    Unexpected token "<eof>" in path expression
[2020-04-21 00:17:16,903] [EI-Core] ERROR - DataMapperMediator DataMapper mediator : mapping failed
javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:220)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:132)
	at net.sf.saxon.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:87)
	at org.wso2.carbon.mediator.datamapper.engine.core.mapper.XSLTMappingHandler.<init>(XSLTMappingHandler.java:46)
	at org.wso2.carbon.mediator.datamapper.DataMapperMediator.transform(DataMapperMediator.java:371)
	at org.wso2.carbon.mediator.datamapper.DataMapperMediator.mediate(DataMapperMediator.java:301)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:260)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:805)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:303)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:578)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:265)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Also Concat operation does not add Delimiter. Hope https://github.com/wso2/devstudio-tooling-esb/pull/1100 is the fix for it. Please verify that as well

**Comment by DMadhuranga** [comment]
Yes, Both issues (more than two inputs and delimiter) are fixed in https://github.com/wso2/devstudio-tooling-esb/pull/1100.
